[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bonding_curve_token = "EpTZy8wg9YC6jerepiebigRXgBSGg3HNH6jBm4gbHj25"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_curve = "npx ts-node ./programs/bonding-curve-token/scripts/init_curve.ts"
buy_tokens = "npx ts-node ./programs/bonding-curve-token/scripts/buy_tokens.ts"
sell_tokens = "npx ts-node ./programs/bonding-curve-token/scripts/sell_tokens.ts"
add_metadata = "npx ts-node ./programs/bonding-curve-token/scripts/add_metadata.ts"